jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  oast:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - |
        cat > .safety-policy.yml <<EOF
        security:
          ignore-vulnerabilities: {}
        EOF
      - run: docker run --rm -v $(pwd):/src hysnsec/safety check -r requirements.txt --json > oast-results.json
      - uses: actions/upload-artifact@v4
        with:
          name: Safety
          path: oast-results.json
        if: always()                        # what is this for?

  release:
    machine: true                                        # What is this for?
    steps:
      - checkout
      - run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t $DOCKER_USERNAME/django.nv .   # Build the application into Docker image
          docker push $DOCKER_USERNAME/django.nv         # Push the image into registry
          
  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          when: on_fail                   # Even if the job fails, continue to the next stages

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a 'deploy' step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - test
      - release
      - integration
      - prod:
          type: approval
          requires:
            - integration
